:doctype: book
:author: KIENAST Lukas
:chapter-label:
:sectnums:
:toc: macro
:toclevels: 2
:toc-title: Inhaltsverzeichnis
:title-separator: any
:url: website.me
:protocol: http
:port: 80
:wordlist_path: wordlist.txt


= Pentesting of {url}
{author}
{docdate}

<<<

toc::[]


== Executive Summary
In einfacher Sprache sollte der Inhalt des Berichts zusammengefasst werden. Ziel dieses Textes sind nicht Techniker, sondern z.B. Management. Nach Lesen des Executive Summaries sollte dieses den Umfang und die Ergebnisse bzw. die Auswirkungen des Penetration-Tests verstehen.

* Was wurde getestet?
* Welche Ergebnisse konnten vorgefunden werden?
* Was sind die potentiellen Auswirkungen? Welchen Einfluss hat das Ergebnis auf den Betrieb der Webseite?
* Empfehlungen?

== Die getestete Anwendung
Hier sollte die getestete Seite kurz beschrieben werden. Falls der Bericht nach mehreren Monaten wieder gelesen wird, ist das ursprüngliche Testziel eventuell nicht mehr nachvollziehbar (URLs können sich auch ändern) bzw. sollte auch die Testumgebung kurz erläutert werden.


* Welche Applikation wurde getestet? Was ist deren Aufgabe?
* Welche Gefährdungen werden gesehen? Vor was hat der Kunde Angst (eigene Annahmen)
* Wer sind die potentielle Angreifer?
* Beschreibung des Ablaufs. Gab es eine Produktiv- oder Test-Umgebung? Durfte destruktiv getestet werden? Gab es Bereiche die nicht getestet werden durften?


== Beschreibung von Schwachstellen und Verbesserungsmaßnahmen

Hier sollten die vorgefundenen Schwachstellen zusammengefasst werden. Ebenso sollte hier eine Übersicht über die vorgeschlagenen Verbesserungsmassnahmen gegeben werden. Dies ist quasi das Gegenstück zur Executive Summary für Techniker


* Welche Schwachstellen wurden vorgefunden?
* Welche Schwachstellen werden besonders kritisch befunden? Eventuell Sortierung der Schwachstellen nach Kritikalität? Tabellen, etc. können hier gerne verwendet werden
* Wie können diese behoben werden?
* Gibt es weitere empfohlene Absicherungsmassnahmen (Hardening)?

== Datensammlung

=== Verbindungssicherheit

Was kann zur Verbindungssicherheit gesagt werden?

* HTTPS/TLS Konfiguration
* wurden Massnahmen zur automatischen Gewährleistung der Verbindungssicherheit (HSTS, CSP, etc.) gesetzt?
* kann z.B. mittels ##https://testssl.sh/## oder ##https://www.ssllabs.com/ssltest/## getestet werden

*Was teste ich bei TLS-Versionen?*

[source,bash,subs="attributes"]
----
# Version 1
openssl s_client -connect {url}:{port} -tls1
# Version 1.1
openssl s_client -connect {url}:{port} -tls1_1
# Version 1.2
openssl s_client -connect {url}:{port} -tls1_2
# Version 1.3
openssl s_client -connect {url}:{port} -tls1_3
----

=== Verwendete HTTP Header

Am besten Ausgabe der verwendeten HTTP-Header (z.b. auf der Startseite oder innerhalb des eingeloggten Bereichs):

*Was teste ich bei httpHeader?*

[source,bash,subs="attributes"]
----
observatory {url} --format=report
----

*plus testssl.sh und Observatory Page*

Anschließend Diskussion der vorgefundenen HTTP-Header. Welche sicherheitsrelevanten Header wurden vorgefunden, welche haben gefehlt. Welche Empfehlungen gibt es? Siehe auch Mozilla Observatory oder https://securityheaders.com/


=== Software-Enumeration

Dieses Kapitel soll die vorgefundenen Softwarekomponenten erwähnen. Hier sollte überprüft werden, ob diese auf dem letzten sicherheitsrelevanten Patch-Level sind bzw. ob es bekannte Exploits für diese Softwarekomponenten bekannt sind.

* Welche Software wurde in welcher Version vorgefunden?
* Gibt es bekannte Schwachstellen?
* Wurden weitere Artefakte (##.git##, Admin-Tools, Backup-Files) vorgefunden?


*Test des Pings*

[source,bash,subs="attributes"]
----
ping {url}
----

*Portscan*
[source,bash,subs="attributes"]
----
sudo nmap -sS -sC -sV -O {url}
----

*Verzeichnisscan*
[source,bash,subs="attributes"]
----
gobuster dir -u {protocol}://{url}:{port} -w {wordlist_path}
----

*Burpsuite Test*

*Owasp Test*

*Automatischer Owasp ZAP Base-Test*

*Automatischer Owasp ZAP API-Test*

*Prüfen ob WAF vorhanden ist*
[source,bash,subs="attributes"]
----
wafw00f {protocol}://{url} -a
----


=== Session, Login/Logout, Authentication

Dieses Kapitel sollte Fragen zum Thema Benutzerverwaltung bzw. Benutzersessions beleuchten.

* Wie werden Benutzersessions abgebildet? Wie wurden diese abgesichert? Schwachstellen und Verbesserungsmassnahmen?
* Gibt es Auffälligkeiten bei Login/Logout?
* Falls Tokens verwendet werden? Wie sind diese aufgebaut? Gibt es hier Probleme?
* Kann man auf Ressourcen ohne Login zugreifen?

*Prüfen welche Authentifikation genutzt wird*

*Prüfen welche Tokens verwendet werden*

*Prüfen ob Tokens ausgehebelt werden können*

=== Berechtigungskonzept

Dieses Kapitel sollte das vorgefundene Berechtigungskonzept genauer erläutern. Es sollte auch (stichprobenweise) getestet werden, ob das Zugriffskonzept auch implementiert wurde (ob Benutzer einer Gruppe wirklich nur auf die Daten und Operationen einer Gruppe zugreifen können. Falls es sich um ein ,,friendly'' Opfer handelt, kann hier auch um einen Administrator-Account gefragt werden. Dieser dient jetzt nicht für den Test direkt, sondern wird verwendet um mögliche Admin-Operationen zu identifizieren auf die dann, als normaler Benutzer, versucht wird zuzugreifen


* Kann ich auf Daten anderer Benutzer zugreifen?
* Kann ich das Profil eines anderen Benutzers modifizieren?

=== Injection-Angriffe

Sammelkapitel für einzelne Injection-Angriffe. Initial sollte bestimmt werden, welche Angriffsvektoren für die getestete Applikation sinnvoll erschienen. So wird z.B. eine LDAP-Injection wahrscheinlich unrealistisch bei einem eCommerce-Shop sein, ebenso wird eine SQL-Injection primär bei einem System mit einem Datenbank-Backend vorkommen. Potentiell können die Angriffe weiters in Client- und Server-Seitige Angriffe aufgeteilt werden.

Typische Fragen:

* Gibt es verwundbare Operationen?
* Wie wurden diese getestet?
* Falls Schwachstellen gefunden wurden, wie können diese ausgebessert werden?

*Testen ob Command Injection möglich ist*

*Testen ob SQL Injection möglich ist*

*Testen ob Directory Traversal möglich ist*

[appendix]
= The Appendix
